language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install: 
    - pip install -r requirements/tests.txt
    - python setup.py install
script: 
    - coverage run --source=xccdf --omit="*tests*,*exception*" setup.py test
    - flake8 src/xccdf
after_success:
    - coverage report -m
    - radon cc -s -a src/xccdf
    - radon mi -s src/xccdf
    - coveralls