language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install: 
    - pip install -r requirements/tests.txt
    - python setup.py install
script: 
    - sh unit_tests.sh
after_success:
    - sh code_quality.sh
    - sh radon.sh
    - coveralls