language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install: 
    - pip install -r requirements/tests.txt
    - python setup.py install
script: 
    - coverage run --source=xccdf --omit="*tests*,*exception*" setup.py test
    - coverage report -m
after_success:
    - flake8 .
    - coveralls